variables:
  REGION: "ap-south-1"


before_script:
  - aws eks update-kubeconfig --name smallcase-dev --region $REGION 
  - aws ecr get-login-password --region "$REGION" | docker login -u AWS --password-stdin "$IAM_ID.dkr.ecr.$REGION.amazonaws.com"


build: 
  tags:
    - Devops
  stage: build
  script: 
    - aws ecr create-repository --repository-name smallcase || echo "REPO ALREADY EXISTS"
    - docker build -t $"smallcase:$CI_COMMIT_SHORT_SHA" .
    - docker tag "smallcase:$CI_COMMIT_SHORT_SHA" "$IAM_ID.dkr.ecr.$REGION.amazonaws.com/smallcase:$CI_COMMIT_SHORT_SHA"
  only:
    - master


deploy-image:
  tags:
    - Devops
  stage: deploy
  script:
    - docker push "$IAM_ID.dkr.ecr.$REGION.amazonaws.com/smallcase:$CI_COMMIT_SHORT_SHA"
  only:
    - master

rollout-changes:
  tags:
    - Devops
  stage: deploy
  script:
    - kubectl set image deployment smallcase "smallcase=$IAM_ID.dkr.ecr.$REGION.amazonaws.com/smallcase:$CI_COMMIT_SHORT_SHA"
  only:
    - master
